server:
  port: 8080

spring:
  application:
    name: gold-rush-service

  datasource:
    url: jdbc:mysql://localhost:3306/deploy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    database: 0
    port: 6379
    password:

logging:
  level:
    com.joosure.deploy.*: info
  file:
    name: logs/deploy.log

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true